### PR TITLE
handle one question per screen on question answer

### PR DESCRIPTION
**Pull request by biyeun**
fyi for @wpride 

along with https://github.com/dimagi/commcare-core/pull/415

attempts to fix the issue where a question is answered in oneQuestionPerScreen mode and the whole question list is sent back rather than the current question

### CODE REVIEW

**Comment by wpride** [comment]
@biyeun Good stuff! I moved the logic into FormSession and switched the commcare-core branch to our spring one but otherwise looks great. Longer term might want the one question per screen stuff in a different package or class, but that's more of a mobile architecture question.

cc @benrudolph

**Comment by wpride** [comment]
(will let you decide on removing don't merge)

**Comment by benrudolph** [comment]
👍 from me, not merging due to label

**Comment by biyeun** [comment]
@wpride is this one no longer relevant then? https://github.com/dimagi/commcare-core/pull/415

**Comment by wpride** [comment]
@biyeun yep

**Comment by biyeun** [comment]
@benrudolph @wpride wanna merge :-D

**Pull request merged**
