### PR TITLE
Revert "Manage MenuSession via Spring Jpa"

### PR DESCRIPTION
**Pull request by gherceg**
Reverts dimagi/formplayer#929

Encountered [this error](https://sentry.io/organizations/dimagi/issues/2354517836/?environment=india&project=142105&query=is%3Aunresolved&statsPeriod=1h) on India. I think [this other error](https://sentry.io/organizations/dimagi/issues/2310922751/?environment=india&project=142105&query=is%3Aunresolved&statsPeriod=1h) is redundant but linking just in case.

@sravfeyn

### CODE REVIEW

**Review by calellowitz — APPROVED** [review]

**Comment by snopoke** [comment]
@sravfeyn I think all that's needed is to add the `menu_session` cache name into `src/main/resource/application.properties`:
```diff
- spring.cache.cache-names=form_session,case_search
+ spring.cache.cache-names=form_session,case_search,menu_session
```

Sorry I didn't pick that up in the PR review.

**Comment by gherceg** [comment]
@snopoke @sravfeyn any idea why this was only an issue on India and not Staging or Swiss?

**Comment by snopoke** [comment]
Only prod and india have caching enabled. I will enable it on staging as well to catch future issues.

**Comment by snopoke** [comment]
https://github.com/dimagi/formplayer/pull/955

**Comment by sravfeyn** [comment]
Thanks for the fix Graham. I made the fix suggested by Simon here https://github.com/dimagi/formplayer/pull/957

**Pull request merged**
