### PR TITLE
Added conditionally required query prompts

### PR DESCRIPTION
**Pull request by orangejenny**
Formplayer support for https://github.com/dimagi/commcare-hq/pull/31568

Depends on https://github.com/dimagi/commcare-core/pull/1106

### CODE REVIEW

**Review by snopoke — APPROVED** [review]

**Review by shubham1g5 — COMMENTED** [review]
A simple test for it can be added in [here](https://github.com/dimagi/formplayer/blob/master/src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java).

**Comment by orangejenny** [comment]
@shubham1g5 This is all web apps UI, though - all formplayer does is pass the values along. Does it seem worth testing?

**Comment by shubham1g5** [comment]
@orangejenny I think we just want to test whether the query response has right value of `required`, for example how we test the blank value [here](https://github.com/dimagi/formplayer/blob/master/src/test/java/org/commcare/formplayer/tests/CaseClaimTests.java#L188).

**Comment by orangejenny** [comment]
Added tests in 9bc22b1f

**Review by shubham1g5 — APPROVED** [review]

**Pull request merged**
