### PR TITLE
Adds hint to case claim prompt

### PR DESCRIPTION
**Pull request by shubham1g5**
[Spec](https://docs.google.com/document/d/1kvav59bn6cAmfPAH0H0cith-dq-iGqfc1IsNOxfUocY/edit)

cross-request: https://github.com/dimagi/commcare-core/pull/974

### CODE REVIEW

**Review by ctsims — APPROVED** [review]

**Review by sravfeyn — APPROVED** [review]

**Comment by sravfeyn** [comment]
I think the build failure is real. Also failing to build locally

```
Sravans-MacBook-Pro:formplayer sravan$ ./gradlew assemble && java -jar build/libs/formplayer.jar
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
/Users/sravan/HQ/formplayer/src/main/java/org/commcare/formplayer/beans/menus/DisplayElement.java:63: error: cannot find symbol
        if (displayUnit.getHintText() != null) {
                       ^
  symbol:   method getHintText()
  location: variable displayUnit of type DisplayUnit
/Users/sravan/HQ/formplayer/src/main/java/org/commcare/formplayer/beans/menus/DisplayElement.java:64: error: cannot find symbol
            this.hint = displayUnit.getHintText().evaluate(ec);
                                   ^
  symbol:   method getHintText()
  location: variable displayUnit of type DisplayUnit
```

**Comment by shubham1g5** [comment]
@sravfeyn  Thanks for pointing, it was missing a commcare-core update, Should be fine now.

**Comment by shubham1g5** [comment]
Ahh, still fails! Digging..

**Comment by shubham1g5** [comment]
all good now!

**Pull request merged**
