### PR TITLE
Added URL encoding to case claim URL

### PR DESCRIPTION
**Pull request by orangejenny**
https://dimagi-dev.atlassian.net/browse/QA-2563

Depends on HQ PR https://github.com/dimagi/commcare-hq/pull/29214

### CODE REVIEW

**Comment by shubham1g5** [comment]
@orangejenny the code [here](https://github.com/dimagi/formplayer/blob/master/src/main/java/org/commcare/formplayer/services/QueryRequester.java#L27) seems to purposefully decode urls. Any idea why would we do that and if this change still takes effect when we are decoding urls later in the code path.

**Comment by orangejenny** [comment]
@shubham1g5 Thanks, I didn't realize that. I think that means the UTF-8 encoding I added isn't doing anything and it's only the URL encoding that's relevant. Removed the URL encoding and retested.

**Comment by shubham1g5** [comment]
@orangejenny  Makes sense. Also wondering if a better change would be to perform URL encoding on the final url [over here](https://github.com/dimagi/formplayer/blob/master/src/main/java/org/commcare/formplayer/services/QueryRequester.java#L19) rather than on the individual params.

**Comment by orangejenny** [comment]
@shubham1g5 I like the idea of acting on the final url instead, but for claiming it's [this one](https://github.com/dimagi/formplayer/blob/91a1a443e096523d5ec0d7fb6e1a437bb390fe04/src/main/java/org/commcare/formplayer/services/SyncRequester.java#L14) where the params are already passed as a request string, and parsing them out seems messy.

**Comment by shubham1g5** [comment]
Ahh I totally forgot this change is for case claim rather than search. Makes sense to me.

**Review by shubham1g5 — APPROVED** [review]

**Pull request merged**
