### PR TITLE
upgrade spring, gradle

### PR DESCRIPTION
**Pull request by snopoke**
* Upgrade Gradle to 5.6.4
* Upgrade Spring Boot to 2.2.0
* Make use of Spring Boot version dependency management: https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/
* Upgrade Flyway

Related changes:
* Make Spring configure JDBC template and Flyway migrations

Cross Requested:
https://github.com/dimagi/commcare-core/pull/870

### CODE REVIEW

**Comment by snopoke** [comment]
Making this 'do not merge' since it will require config changes to be rolled out first.

**Comment by snopoke** [comment]
Compilation of `commcare` failing:
```
> Task :commcare:compileTranslateJava FAILED
/home/travis/build/dimagi/formplayer/libs/commcare/src/translate/java/org/javarosa/engine/xml/XmlUtil.java:32: error: no suitable constructor found for OutputFormat(Document)
            OutputFormat format = new OutputFormat(document);
                                  ^
    constructor OutputFormat.OutputFormat() is not applicable
      (actual and formal argument lists differ in length)
    constructor OutputFormat.OutputFormat(String,String,boolean) is not applicable
      (actual and formal argument lists differ in length)
```
@shubham1g5 I think this is a Java version issue - what version should this be compiled against?

**Comment by millerdev** [comment]
LGTM so far

**Comment by ctsims** [comment]
@snopoke Got tests passing, and fixed a CORS misconfiguration, I think this is now just blocking on coordinating how to get configurations updated.

**Comment by snopoke** [comment]
I've reverted the changes that require updates to the config so that we can roll those out separately.

**Comment by ctsims** [comment]
Great, thanks @snopoke 

Heads up that to keep the heads consistent we try to apply all cross-requested PR's between commcare-core's `formplayer` branch and formplayer at the same time (the head will stay consistent anyway, but then it's not a detached commit)

**Pull request merged**
