### PR TITLE
use session details view for auth

### PR DESCRIPTION
**Pull request by snopoke**
Instead of looking up the session in the Django DB we call a service on HQ to get the user details we need.

Can review by commit :fish: 

cc @benrudolph (for kicks)

### CODE REVIEW

**Comment by wpride** [comment]
@snopoke Woah, this is awesome! Removing the HQPostgres and Couch dependencies is huge!

**Comment by snopoke** [comment]
There's some more cleanup to do still but I thought I'd leave that for
another PR

**Comment by snopoke** [comment]
Merging now that HQ endpoint has been deployed as well as auth keys changes

**Comment by snopoke** [comment]
deployed this to prod - looking good so far

**Pull request merged**
