### PR TITLE
use correct helper function

### PR DESCRIPTION
**Pull request by snopoke**
https://manage.dimagi.com/default.asp?250785

Depends on https://github.com/dimagi/commcare-core/pull/543

### CODE REVIEW

**Comment by snopoke** [comment]
Note: this code isn't tested - wasn't clear to me how to go about that.

**Comment by snopoke** [comment]
Also note that I wasn't sure how to update the version of `commcare-core`. Some docs on how the dev process works for formplayer would be useful.

**Comment by benrudolph** [comment]
thanks simon, this is something i've been trying to work on. we do have a process, but right now isn't written up. i'll add that to the docs. there should be a branch on `commcare-core` called `nimbus` that acts as the `master` branch. all major commcare version upgrades and nimbus only changes get PR'd into that branch

this bug i believe is actually already fixed in here: https://github.com/dimagi/formplayer/pull/333 (but was causing other issues so needed i needed to revert it)

**Comment by snopoke** [comment]
Closed in favour of https://github.com/dimagi/formplayer/pull/333

**Pull request closed without merging**
