### PR TITLE
Make force restore overwrite cache

### PR DESCRIPTION
**Pull request by benrudolph**
@czue @wpride http://manage.dimagi.com/default.asp?245357#1272630 I _think_ this is the root cause. trying to validate. next step is figuring out if it's safe to deploy formplayer. we may need to make a PR off of the commit deployed to icds

### CODE REVIEW

**Comment by czue** [comment]
nice, makes sense to me. build is failing, not sure if related

**Comment by benrudolph** [comment]
✅ can anyone who merges this use squash commit (or just approve and i'll squash)

**Comment by benrudolph** [comment]
actually hold off for a second

**Comment by wpride** [comment]
Nice tests refactor

**Pull request merged**
