### PR TITLE
Fix and Revert "Revert "Manage MenuSession via Spring Jpa"" 

### PR DESCRIPTION
**Pull request by sravfeyn**

### CODE REVIEW

**Comment by snopoke** [comment]
@sravfeyn we should try get this pushed out

**Comment by sravfeyn** [comment]
Yes, I have resolved the conflict now.

**Review by snopoke — APPROVED** [review]
Once this is merged can you please rebuild the staging branch and do a staging deploy to confirm the issue is fully resolved.

**Comment by sravfeyn** [comment]
I have deployed this on staging and haven't seen that error so far.

**Comment by sravfeyn** [comment]
Do you know of any particular reproduction steps?

**Comment by snopoke** [comment]
> Do you know of any particular reproduction steps?

If navigation through an app works then I think we're GTG.

**Comment by sravfeyn** [comment]
Yes, it does!

**Pull request merged**
