### PR TITLE
Complimentary Changes for Formplayer 2.50 

### PR DESCRIPTION
**Pull request by shubham1g5**
Corresponding changes required for the [master merge](https://github.com/dimagi/commcare-core/pull/966)

### CODE REVIEW

**Review by orangejenny — APPROVED** [review]

**Comment by ctsims** [comment]
Suggestion: I think we should set this PR to target the new merged head in `commcare-core` as is, and have this PR be what is merged to bring in the cc-core update into formplayer as well. We'll need to have a PR whcih updates the cc-core head anyway, since the `formplayer` branch name being updated is just a convention.

**Comment by shubham1g5** [comment]
@ctsims do you mean just point the submodule to latest commit in core's `master` without waiting for https://github.com/dimagi/commcare-core/pull/966 to be merged in core's `formplayer` ? I agree they both are same though just wanna confirm if this is what you meant.

**Comment by ctsims** [comment]
I mean pointing the submodule to the head of https://github.com/dimagi/commcare-core/pull/966 since that's what will be the new `formplayer` branch head once the PR is merged, and I think that merge needs to happen before this code is valid, right?

**Comment by shubham1g5** [comment]
@ctsims yup, that makes sense.

**Review by ctsims — APPROVED** [review]

**Comment by orangejenny** [comment]
QA is complete.

**Pull request merged**
