### PR TITLE
Ignore this goddamn exception

### PR DESCRIPTION
**Pull request by wpride**
Really this is the wrong exception to be thrown but the fix is deep in the engine and I don't think this will ever be a "real" 500 so

### CODE REVIEW

**Comment by czue** [comment]
haha this has gotta be related to case claim

**Comment by wpride** [comment]
@czue haha nope this is ~entirely related to app config errors, usually misconfigured parens or quotes in the suite that form builder misses. Occasionally we get bombed with them

**Comment by orangejenny** [comment]
A+ PR naming, I can feel your pain all the way from Boston.

**Comment by snopoke** [comment]
Can you give an example? Might be able to fix it on HQ as well.

**Comment by wpride** [comment]
lol take your pick: https://groups.google.com/a/dimagi.com/forum/#!searchin/commcarehq-ops/UnresolvedResourceException%7Csort:date

Derek seems to have had about forty tonight

**Comment by snopoke** [comment]
Hmm, I think it would be expensive for HQ to validate all of those unless we build a bulk xpath validation endpoint into Nimbus.

**Pull request merged**
