### PR TITLE
manually deregister JDBC drivers

### PR DESCRIPTION
**Pull request by wpride**
@benrudolph this also should help with memory leaks

### CODE REVIEW

**Comment by benrudolph** [comment]
awesome :non-potable_water:

**Comment by snopoke** [comment]
A bit confused by this - why do we need to de-register the drivers? Can't we just not include them in the first place?

**Comment by wpride** [comment]
@snopoke we use the JDBC drivers to interact with the sqlite dbs so the class loader will register these classes, not sure how we'd get around that?

**Comment by snopoke** [comment]
Ah right - I missed one key detail: `@PreDestroy`. Still seems a bit strange that we'd need to do this since we aren't running in a container. But I'll assume its right.

**Pull request merged**
