### PR TITLE
use long detail for detail screen

### PR DESCRIPTION
**Pull request by jmtroth0**
@ctsims @dannyroberts

### CODE REVIEW

**Comment by jmtroth0** [comment]
https://github.com/dimagi/commcare-core/pull/835 needs to be pulled in before merging this

**Comment by jmtroth0** [comment]
bumping this for review. or maybe @shubham1g5

**Comment by ctsims** [comment]
@jmtroth0 What's the user facing behavior as a results of this change when there's no long detail defined? It doesn't look like it falls back intentionally to the short detail, does it skip it entirely?

**Comment by jmtroth0** [comment]
It would have just skipped it entirely. Now it will fall back to the short detail, although I'm not sure how to test that since I'm not sure how to create the case where there is no LongDetail

**Comment by ctsims** [comment]
@jmtroth0 you can create a "no long detail" scenario on HQ by just deleting all of the fields on the Case Detail config to test your scenario. 

Signed off as soon as it's confirmed that that works.

**Comment by ctsims** [comment]
Hm, wait, I think I misunderstood.

"Skip entirely" (IE: "I click on the row and then immediately am done with detail selection") is the right behavior for a missing long detail, so if that's what happens when it's missing we should do that (after confirming)

**Comment by jmtroth0** [comment]
Ok, that works now, skipping the detail page if there isn't any data on it.

**Pull request merged**
