### PR TITLE
Add hidden attr to query prompt and display

### PR DESCRIPTION
**Pull request by sravfeyn**
@shubham1g5 

cross-request: https://github.com/dimagi/commcare-core/pull/996

https://docs.google.com/document/d/1n34UU73EMFe5EnbtIaLXsIeFOHY3J3iXnf27GOZhBQE/edit#

### CODE REVIEW

**Review by shubham1g5 — APPROVED** [review]

**Comment by snopoke** [comment]
@sravfeyn can you link to the spec / ticket for this - just to give more context on the use case

**Comment by sravfeyn** [comment]
@shubham1g5 Do you think this and https://github.com/dimagi/commcare-core/pull/996 needs to be part of QA or could directly be merged?

**Comment by shubham1g5** [comment]
@sravfeyn The changes looks safe to me as such, though if the feature is anyway undergoing QA, unless there is a specific reason it's good to get them all through QA before merging.

**Comment by sravfeyn** [comment]
QA is finished.

**Pull request merged**
