### PR TITLE
Update commcare-core reference

### PR DESCRIPTION
**Pull request by gherceg**
Updating to latest commit on `formplayer` branch to include https://github.com/dimagi/commcare-core/pull/1079

### CODE REVIEW

**Comment by gherceg** [comment]
Interesting compile time failure 🤔 
```
/home/runner/work/formplayer/formplayer/src/main/java/org/commcare/formplayer/screens/FormplayerSyncScreen.java:44: error: incompatible types: Multimap<String,String> cannot be converted to Hashtable<String,String> 
Hashtable<String, String> params = syncPost.getEvaluatedParams(sessionWrapper.getEvaluationContext());
```

**Comment by snopoke** [comment]
> Interesting compile time failure 🤔
> 
> ```
> /home/runner/work/formplayer/formplayer/src/main/java/org/commcare/formplayer/screens/FormplayerSyncScreen.java:44: error: incompatible types: Multimap<String,String> cannot be converted to Hashtable<String,String> 
> Hashtable<String, String> params = syncPost.getEvaluatedParams(sessionWrapper.getEvaluationContext());
> ```

That's because of a change I made which is still in PR on this repo: https://github.com/dimagi/formplayer/pull/1107. I just merged that so you might have a conflict but the building should pass once it's resolved.

**Comment by snopoke** [comment]
@gherceg I've merged another commcare-core branch into the `formplayer` which is fine to update into the formplayer repo.

**Review by snopoke — APPROVED** [review]

**Comment by gherceg** [comment]
That test failure is on me. Looking.

**Comment by gherceg** [comment]
@snopoke fyi I haven't had time to solve this. If your formplayer change is dependent on this commcare-core update and needs to be merged before the deploy tomorrow, then I can revert my commcare-core change and update the formplayer branch.

**Comment by snopoke** [comment]
@gherceg to fix the tests you'd need to bump the DB version number (https://github.com/dimagi/formplayer/commit/bf2ff7ae12ae73a67239773556d1b14f360f5523) and update the test DB names (https://github.com/dimagi/formplayer/commit/177d1a1113cd3064b7fbb409080ba60fbf53a50f)

**Comment by snopoke** [comment]
@shubham1g5 looking at the test failures I'm a bit confused as to why the userDB test breaks. Do we store FormInstances in the userDB?

Looking at the error traces they both seem to come from loading fixtures which is also confusing but it looks like we store form instances as fixtures, is that right?

**Comment by snopoke** [comment]
@shubham1g5 looking at the test failures I'm a bit confused as to why the userDB test breaks. Do we store FormInstances in the userDB?

Looking at the error traces they both seem to come from loading fixtures which is also confusing but it looks like we store form instances as fixtures, is that right?

**Comment by shubham1g5** [comment]
@snopoke that's right, fixtures seems to use the `FormInstance` model and are part of [user DB.](https://github.com/dimagi/formplayer/blob/master/src/main/java/org/commcare/formplayer/sandbox/UserSqlSandbox.java#L56-L57)

**Pull request closed without merging**
