### PR TITLE
remove specific app config loading

### PR DESCRIPTION
**Pull request by wpride**
@benrudolph

### CODE REVIEW

**Comment by benrudolph** [comment]
👍

**Comment by benrudolph** [comment]
should i add this to the staging file?

**Comment by wpride** [comment]
@benrudolph add what?

**Comment by benrudolph** [comment]
i was gonna say let's test this on staging by adding the branch... but then i realized we can't test it on staging because formplayer build comes from jenkins

**Comment by benrudolph** [comment]
tested this out on staging and it works

**Pull request merged**
