### PR TITLE
Allow searching for Blank values

### PR DESCRIPTION
**Pull request by shubham1g5**
[Feature Design](https://docs.google.com/document/d/1sLHXEFPfj56zcLw8ZZPDXMVOUxqHiIpxKIcp2hE2ueE/edit?ts=60edcb77)

https://dimagi-dev.atlassian.net/browse/USH-1105

Do 2 distinct things - 

1. Pass on `allow_blank_value` to Web Apps so that Web Apps can display an additional checkbox for blank value search based on this
2. Make a distinction between empty and null values in code and verifies it through tests. A missing 'key' in the `queryData` object from web apps is treated as no-value and Formplayer doesn't include it in search while a key with empty string value is propogated to search as it is. 

QA ticket: https://dimagi-dev.atlassian.net/browse/QA-3205

cross-request: https://github.com/dimagi/commcare-core/pull/1017
HQ- https://github.com/dimagi/commcare-hq/pull/30309

### CODE REVIEW

**Review by snopoke — APPROVED** [review]

**Review by sravfeyn — APPROVED** [review]

**Comment by esoergel** [comment]
FYI the build is failing, and I see the same failure when trying to build locally:
```
> Task :compileJava
/home/travis/build/[secure]/formplayer/src/main/java/org/commcare/formplayer/beans/menus/QueryResponseBean.java:72: error: cannot find symbol
                    queryPromptItem.isAllowBlankValue());
                                   ^
  symbol:   method isAllowBlankValue()
  location: variable queryPromptItem of type QueryPrompt
```
It looks like a real issue

**Comment by shubham1g5** [comment]
@esoergel You will need to point the submodule in `libs/commcare` to the `allowBlankSearch` branch.

**Comment by esoergel** [comment]
Ah, that makes sense, working for me now, thanks @shubham1g5

**Review by ctsims — COMMENTED** [review]
Feedback over email.

**Pull request merged**
