### PR TITLE
Triggerables bug fix

### PR DESCRIPTION
**Pull request by wpride**
Potential fix for https://manage.dimagi.com/default.asp?261963

Makes intuitive sense to me and seems to be what Android is doing, but want to make sure I understand this change better before merging.

### CODE REVIEW

**Comment by ctsims** [comment]
I'm confused. What does this have to do with triggerables?

**Comment by wpride** [comment]
offlined with @ctsims and made changes

**Comment by ctsims** [comment]
Hey Will- where are the mobile changes ? They should be x requested riht?

**Comment by wpride** [comment]
@ctsims PR https://github.com/dimagi/commcare-core/pull/660

**Comment by dannyroberts** [comment]
```
error: Server does not allow request for unadvertised object d1676ea35a5af105631f98baefb7d55f905d38cf
Fetched in submodule path 'libs/commcare', but it did not contain d1676ea35a5af105631f98baefb7d55f905d38cf. Direct fetching of that commit failed.
```

maybe you didn't push your local submodule code?

**Comment by dannyroberts** [comment]
@wpride still working on this? (not mergeable)

**Pull request closed without merging**
