### PR TITLE
More optimisations for Entity list performance

### PR DESCRIPTION
**Pull request by shubham1g5**
## Technical Summary

We were calculating the display properties for Entities on the current page twice. Once as part of [buildEntityList](https://github.com/dimagi/formplayer/blob/master/src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java#L225) and then again while [processEntity](https://github.com/dimagi/formplayer/blob/master/src/main/java/org/commcare/formplayer/beans/menus/EntityListResponse.java#L287) to build a `EntityBean`. This PR changes the code to directly take use of `Entity` object evaluated fields to build the `EntityBean`

### Safety story

Mostly relying on unit test coverage

### Automated test coverage

A good number of navigation tests touches and tests over `EntityListResponse`

### QA Plan

None

### Special deploy instructions

- [x] This PR can be deployed after merge with no further considerations.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations.

### Review

- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### CODE REVIEW

**Review by snopoke — APPROVED** [review]
Looking at the `NoteEntityFactory` class it seems like there is quite a bit more cleanup that could be done in the future.

**Comment by shubham1g5** [comment]
> Looking at the NoteEntityFactory class it seems like there is quite a bit more cleanup that could be done in the future.

curious what exactly are you thinking ?

**Comment by snopoke** [comment]
> > Looking at the NoteEntityFactory class it seems like there is quite a bit more cleanup that could be done in the future.
> 
> curious what exactly are you thinking ?

I was mostly thinking that there is a fair amount of duplication between what's being done in EntityListResponse and in NoteEntityFactory.

It also seems like NoteEntityFactory was intended to be subclassed at some point but it isn't now and has some unused methods.

**Comment by shubham1g5** [comment]
> It also seems like NoteEntityFactory was intended to be subclassed at some point but it isn't now and has some unused methods.

It actually gets subclassed on [mobile](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/models/AsyncNodeEntityFactory.java)

**Pull request merged**
