### PR TITLE
server up route for formplayer

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride look ma! i wrote java code!

### CODE REVIEW

**Comment by benrudolph** [comment]
somehow formplayer spell corrected to kingdom..

**Comment by wpride** [comment]
👍  :tight: 🔥  
because it is our kingdom 👑 👸

**Comment by wpride** [comment]
👍 on ✅

**Comment by benrudolph** [comment]
✔️

**Comment by benrudolph** [comment]
👑 📝 📝 📝 👑

**Comment by czue** [comment]
:coffee: :crown:

**Pull request merged**
