### PR TITLE
CommCare 2.37 on Formplayer

### PR DESCRIPTION
**Pull request by wpride**
cross-request: https://github.com/dimagi/commcare-core/pull/612

### CODE REVIEW

**Comment by wpride** [comment]
@ctsims can you confirm this looks alright?

**Comment by benrudolph** [comment]
💰 tests failure
https://github.com/dimagi/commcare-core/pull/612

**Comment by ctsims** [comment]
Fixed the cross-reference, seeing if that fixes the build (the failure is build tool realted)

**Comment by ctsims** [comment]
@damagatchi retest this please

**Pull request merged**
