### PR TITLE
Update submodule again

### PR DESCRIPTION
**Pull request by wpride**
Remove more unused functions towards `commcare-core` parity

### CODE REVIEW

**Comment by amstone326** [comment]
@wpride I don't see a PR for the core change. Can you make one or point to where it is if I'm missing it?

**Comment by wpride** [comment]
@amstone326 I pushed them directly to `formplayer` in my haste, you can view the diff here https://github.com/dimagi/commcare-core/compare/41a371b16614997a6163695463b28662c22715d1...065507cf92ae978def16d736d380d17815342a35

**Comment by dannyroberts** [comment]
In addition to removing some methods, you also changed the signature of `getNonMainInstances`. Is that intentional?

**Comment by wpride** [comment]
@dannyroberts Nice catch, and yes - that's the signature in `master`

**Pull request merged**
