### PR TITLE
update readme for mac specific issue

### PR DESCRIPTION
**Pull request by Robert-Costello**
## Technical Summary

Mac users running formplayer outside of Docker (all mac users?) need to remove references to `micrometer` to run formplayer locally. I was reminded of this when helping new devs setup their environments. 

## Safety Assurance
Just a readme change
### QA Plan

no QA
### Migrations

- [x] This PR can be deployed after merge with no further considerations.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations.

### Review

- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### CODE REVIEW

**Comment by orangejenny** [comment]
Could this be an OS version issue? I'm on Monterey (12.5) and don't need to do this.

**Comment by stephherbers** [comment]
hm I also don't have to do this-- interesting. Is it a M1 chip issue?

**Comment by Robert-Costello** [comment]
Interesting, thanks for the input. This was a fix that Sravan came up with last year so it could be an OS version thing. I'm on an intel machine running Big Sur 11.3, so I don't think it's exclusive to M1 machines. I'll check with Evan and Jonathan to see what version they're running.

**Comment by Robert-Costello** [comment]
Evan is on Monterey 12.5.1

**Comment by orangejenny** [comment]
Weird. How about just updating the docs to say "Mac users **may** need..."?

**Comment by Robert-Costello** [comment]
Thanks @AddisonDunn. That deepens the mystery, but is definitely helpful info.

**Review by orangejenny — APPROVED** [review]

**Comment by shubham1g5** [comment]
This might also be related to the combination of M1 chip and the Java variant they are using. Do we know if they are using a Java distribution other than OpenJDK ?

**Pull request merged**
