### PR TITLE
Serialize nodes

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride @ctsims this serializes nodes returned to the debugger in XML. i've already found it to be very useful. it also adds autocomplete options for instance declarations if it knows them. hold off on merge as it needs to be formatted properly on HQ side

### CODE REVIEW

**Comment by ctsims** [comment]
Nice! @wpride Am wondering whether we can shift this code into a place where we will be able to take advantage of it for the CLI as well?

**Comment by wpride** [comment]
This is awesome! Agreed we should get this into `core` too

**Comment by wpride** [comment]
@benrudolph failing. shibby!

**Comment by benrudolph** [comment]
needs this guy: https://github.com/dimagi/commcare-core/pull/589

**Pull request merged**
