### PR TITLE
Force restore when loading a new form

### PR DESCRIPTION
**Pull request by benrudolph**
@wpride this ensure we do a restore on editing a form

### CODE REVIEW

**Comment by wpride** [comment]
I don't think we want this, this will cause a restore to be triggered every time someone menu navs from a form list to a form

**Comment by wpride** [comment]
Wait NVM I think you're right, totally separate route

**Comment by benrudolph** [comment]
Yeah that's the conclusion I came to

**Comment by benrudolph** [comment]
(i think our tests are broken)

**Comment by wpride** [comment]
@benrudolph I think this change is actually causing that

**Comment by benrudolph** [comment]
haha shit, will take a look. test didn't seem related

**Comment by wpride** [comment]
Just guessing based on that test using this endpoint (new-form). Actually
not sure if test was always wrong and was testing the wrong thing... very
possible

**Pull request merged**
